spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=homework
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver